/**
 * Hardcoded BLARF rounds for local development and testing.
 * In production, packs are created via the pack creator UI.
 * Each round: a letter + 15 Seuss-style nonsense words starting with that letter.
 */

import type { BlarfRoundData } from "./blarfTypes";

export const DEFAULT_BLARF_ROUNDS: BlarfRoundData[] = [
  {
    letter: "S",
    words: [
      "Snozzwang",
      "Snipplefrix",
      "Snoofledorp",
      "Skwibbleflop",
      "Snurtlegurk",
      "Splindlewonk",
      "Squazzlebert",
      "Snibblewicket",
      "Splotchkinz",
      "Skrunkledorf",
      "Snifferwhump",
      "Spazzlequirk",
      "Slurpledink",
      "Snorklefizz",
      "Swomplegust",
    ],
  },
  {
    letter: "G",
    words: [
      "Glorpfizzle",
      "Gricklewump",
      "Grumblesnatch",
      "Gooblewhack",
      "Gnarfledooze",
      "Glimbersnort",
      "Gunklewitz",
      "Gazorpletink",
      "Grozzlebop",
      "Gibblefronk",
      "Gwobblejinx",
      "Glinkerplop",
      "Grindlesnuff",
      "Gulpitywonk",
      "Gazzlefump",
    ],
  },
  {
    letter: "B",
    words: [
      "Blorftangle",
      "Bumblequark",
      "Bricklesnotz",
      "Bogglewump",
      "Blinkerfudge",
      "Bozzlethwip",
      "Brumplesnick",
      "Bafflegronk",
      "Bimblequat",
      "Blunderspork",
      "Borklefratz",
      "Bunglewitz",
      "Bristleplonk",
      "Blooperdink",
      "Bazzlethump",
    ],
    voiceStyle: "shout",
  },
  {
    letter: "F",
    words: [
      "Fizzlewhonk",
      "Flumperdink",
      "Frobnicator",
      "Fwibblesnort",
      "Fronkleberry",
      "Flozzlegrip",
      "Fumblequirk",
      "Fazzlewump",
      "Flickerplonk",
      "Frazzletwig",
      "Foonglesnap",
      "Fribblezork",
      "Flumgustard",
      "Fwozzlekink",
      "Funkledorp",
    ],
    voiceStyle: "whisper",
  },
  {
    letter: "W",
    words: [
      "Wumblefrizz",
      "Wozzlethunk",
      "Whimbleplop",
      "Winkerdooze",
      "Wacklegurp",
      "Wobblesnitch",
      "Wrangletorp",
      "Wiffleblonk",
      "Wunklespatz",
      "Wazzlefrump",
      "Whomblegritz",
      "Wigglesnork",
      "Wubbleflink",
      "Woofledank",
      "Wrinkleplonk",
    ],
    voiceStyle: "sing",
  },
  {
    letter: "Z",
    words: [
      "Zinklewhomp",
      "Zazzlefronk",
      "Zorplegrist",
      "Zibblequank",
      "Zwonklefizz",
      "Zrumblethwip",
      "Zoggleplix",
      "Zwicklesnort",
      "Zunkleberg",
      "Zrazzleplop",
      "Zimplewonk",
      "Zorkledink",
      "Zufflegrump",
      "Zinglebonk",
      "Zwibbleflap",
    ],
    voiceStyle: "dramatic",
  },
  {
    letter: "P",
    words: [
      "Plonkerfizz",
      "Prizzlethwack",
      "Pumblesnort",
      "Porklewitz",
      "Pazzledorf",
      "Plimblegurk",
      "Pronklefudge",
      "Pifflewhomp",
      "Puzzlegrunk",
      "Plozzlequirk",
      "Prumblesnick",
      "Pwicklethump",
      "Panglefrost",
      "Pibblezork",
      "Plooflegust",
    ],
    voiceStyle: "robot",
  },
];
