import type { IdeogramStylePresetV3 } from "./ideogramImageTypes";

function labelFromPreset(p: Exclude<IdeogramStylePresetV3, "">): string {
  return p.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

const PRESETS: Exclude<IdeogramStylePresetV3, "">[] = [
  "80S_ILLUSTRATION",
  "90S_NOSTALGIA",
  "ABSTRACT_ORGANIC",
  "ANALOG_NOSTALGIA",
  "ART_BRUT",
  "ART_DECO",
  "ART_POSTER",
  "AURA",
  "AVANT_GARDE",
  "BAUHAUS",
  "BLUEPRINT",
  "BLURRY_MOTION",
  "BRIGHT_ART",
  "C4D_CARTOON",
  "CHILDRENS_BOOK",
  "COLLAGE",
  "COLORING_BOOK_I",
  "COLORING_BOOK_II",
  "CUBISM",
  "DARK_AURA",
  "DOODLE",
  "DOUBLE_EXPOSURE",
  "DRAMATIC_CINEMA",
  "EDITORIAL",
  "EMOTIONAL_MINIMAL",
  "ETHEREAL_PARTY",
  "EXPIRED_FILM",
  "FLAT_ART",
  "FLAT_VECTOR",
  "FOREST_REVERIE",
  "GEO_MINIMALIST",
  "GLASS_PRISM",
  "GOLDEN_HOUR",
  "GRAFFITI_I",
  "GRAFFITI_II",
  "HALFTONE_PRINT",
  "HIGH_CONTRAST",
  "HIPPIE_ERA",
  "ICONIC",
  "JAPANDI_FUSION",
  "JAZZY",
  "LONG_EXPOSURE",
  "MAGAZINE_EDITORIAL",
  "MINIMAL_ILLUSTRATION",
  "MIXED_MEDIA",
  "MONOCHROME",
  "NIGHTLIFE",
  "OIL_PAINTING",
  "OLD_CARTOONS",
  "PAINT_GESTURE",
  "POP_ART",
  "RETRO_ETCHING",
  "RIVIERA_POP",
  "SPOTLIGHT_80S",
  "STYLIZED_RED",
  "SURREAL_COLLAGE",
  "TRAVEL_POSTER",
  "VINTAGE_GEO",
  "VINTAGE_POSTER",
  "WATERCOLOR",
  "WEIRD",
  "WOODBLOCK_PRINT",
];

export const STYLE_PRESET_OPTIONS: { value: IdeogramStylePresetV3; label: string }[] = [
  { value: "", label: "None (use style type only)" },
  ...PRESETS.map((value) => ({ value, label: labelFromPreset(value) })),
];
